# Generated by Django 5.2.15 on 2026-06-21 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_entregabeneficiario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('arquivo', models.FileField(upload_to='documentos_importados/')),
                ('tipo', models.CharField(choices=[('EXCEL', 'Excel'), ('WORD', 'Word'), ('PDF', 'PDF'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('texto_extraido', models.TextField(blank=True, null=True)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='gestao.documentoimportado')),
            ],
        ),
    ]
