# Generated by Django 5.2.15 on 2026-06-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_documentoimportado_registroimportado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoimportado',
            name='tipo_importacao',
            field=models.CharField(choices=[('PRODUTOS', 'Produtos'), ('DOADORES', 'Doadores'), ('BENEFICIARIOS', 'Beneficiários'), ('DOACOES', 'Doações'), ('ESTOQUE', 'Estoque'), ('CAMPANHAS', 'Campanhas')], default=2, max_length=30),
            preserve_default=False,
        ),
    ]
