# Generated by Django 5.2.15 on 2026-06-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_documentoimportado_tipo_importacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproduto',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='documentoimportado',
            name='tipo_importacao',
            field=models.CharField(choices=[('PRODUTOS', 'Produtos'), ('DOADORES', 'Doadores'), ('BENEFICIARIOS', 'Beneficiários'), ('DOACOES', 'Doações'), ('ESTOQUE', 'Estoque'), ('CAMPANHAS', 'Campanhas')], default='PRODUTOS', max_length=30),
        ),
    ]
